const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const sourcePath = path.join(root, 'theme', 'tokens.json')
const targetPath = path.join(root, 'src', 'shared', 'theme', 'tokens.generated.css')
const sourceRoot = path.join(root, 'src')
const required = ['background', 'foreground', 'surface', 'card', 'popover', 'primary', 'primary-foreground', 'primary-hover', 'secondary', 'secondary-foreground', 'muted', 'muted-foreground', 'accent', 'accent-foreground', 'selected', 'border', 'input', 'ring', 'destructive', 'destructive-foreground', 'media-background', 'media-foreground', 'scrollbar', 'overlay']

function toHsl(hex) {
  const value = hex.slice(1)
  const r = parseInt(value.slice(0, 2), 16) / 255
  const g = parseInt(value.slice(2, 4), 16) / 255
  const b = parseInt(value.slice(4, 6), 16) / 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b), lightness = (max + min) / 2
  if (max === min) return `0 0% ${(lightness * 100).toFixed(1)}%`
  const delta = max - min
  const saturation = delta / (1 - Math.abs(2 * lightness - 1))
  const hue = max === r ? ((g - b) / delta) % 6 : max === g ? (b - r) / delta + 2 : (r - g) / delta + 4
  return `${Math.round((hue * 60 + 360) % 360)} ${Math.round(saturation * 100)}% ${Math.round(lightness * 100)}%`
}

const tokens = JSON.parse(fs.readFileSync(sourcePath, 'utf8'))
const themes = tokens.themes || {}
const names = ['light', 'dark']
const invalid = names.flatMap(theme => required.filter(name => !/^#[0-9a-fA-F]{6}$/.test(themes[theme]?.colors?.[name] || '')).map(name => `${theme}.${name}`))
if (invalid.length || names.some(theme => !Number.isFinite(themes[theme]?.opacity?.overlay) || themes[theme].opacity.overlay < 0 || themes[theme].opacity.overlay > 1)) throw new Error(`Invalid theme tokens: ${invalid.join(', ') || 'opacity.overlay'}`)
const block = (selector, theme) => `${selector} {\n  color-scheme: ${theme};\n${required.map(name => `  --${name}: ${toHsl(themes[theme].colors[name])};`).join('\n')}\n  --overlay-opacity: ${themes[theme].opacity.overlay};\n  --radius: 0.5rem;\n}`
const css = `/* Generated by scripts/generate-theme.cjs. Do not edit directly. */\n${block(':root', 'light')}\n\n${block(':root[data-theme="dark"]', 'dark')}\n`
if (process.argv.includes('--check')) {
  if (!fs.existsSync(targetPath) || fs.readFileSync(targetPath, 'utf8') !== css) throw new Error('Generated theme CSS is out of date. Run pnpm theme:generate.')
  const files = []
  const visit = directory => fs.readdirSync(directory, {withFileTypes: true}).forEach(entry => {
    const next = path.join(directory, entry.name)
    if (entry.isDirectory()) return visit(next)
    if (/\.(js|jsx|css)$/.test(entry.name)) files.push(next)
  })
  visit(sourceRoot)
  const exceptions = new Set([path.join(sourceRoot, 'features', 'export', 'components', 'ExportView.jsx')])
  const hardcoded = files.filter(file => !exceptions.has(file) && !file.endsWith('tokens.generated.css')).filter(file => /#[0-9a-fA-F]{3,8}\b/.test(fs.readFileSync(file, 'utf8')))
  if (hardcoded.length) throw new Error(`Theme colors must use tokens: ${hardcoded.map(file => path.relative(root, file)).join(', ')}`)
} else {
  fs.mkdirSync(path.dirname(targetPath), {recursive: true})
  fs.writeFileSync(targetPath, css)
}
